### ISSUE TITLE
Pluralize.dll not unpacked

### ISSUE THREAD

**Issue by Deveritas** [quepland2/quepland2.github.io#1]
When loading the page, there is a 404 error when the game tries to load /_framework/_bin/Pluralize.NET.dll.

When looking in the _bin directory, all the other resources are in three parts - .dll, .dll.br, and .dll.gz; Pluralize.NET only has two of the three: .br  and .gz. The bare .dll is missing.

This looks like a simple unpack error from the 1.0.6 update.

**Comment by billybillyjim** [comment]
Thanks for this. Unfortunately even adding the missing dll didn't fix the issue. Not sure if it's just a caching problem or what, but for now I'll just be using a build without it.
